#include "Problem.hpp"

#include <iostream>
#include <cassert>
#include <ctime>

#include "Output.hpp"
#include "Options.hpp"

namespace logic {
    
    void ReasoningTask::outputSMTLIB(std::ostream& ostr) const
    {
        auto smtlibLogic = "UFDTLIA"; // uninterpreted functions, datatypes and linear integer arithmetic
        
        // if encoding is used as smtlib-benchmark, add meta information
        if(util::Configuration::instance().generateBenchmark().getValue())
        {
            ostr << "(set-info :smt-lib-version 2.6)\n";
            ostr << "(set-logic " << smtlibLogic << ")\n";

            std::time_t t = std::time(0);
            std::tm* now = std::localtime(&t);

            ostr << "(set-info :source |\n"
            << "Generated by: Bernhard Gleiss\n"
            << "Generated on: "
            << (now->tm_year + 1900) << "-"
            << (now->tm_mon + 1) << "-"
            << now->tm_mday << "\n"
            << "Generator: Rapid\n"
            << "Application: Software Verification\n"
            << "Target solver: Vampire\n"
            << "|)\n"
            << "(set-info :license \"https://creativecommons.org/licenses/by/4.0/\")\n"
            << "(set-info :category crafted)\n"
            << "(set-info :status unknown)\n\n";
        }
        else
        {
            ostr << "\n(set-logic " << smtlibLogic << ")\n\n";
        }
        
        // output sort declarations
        for(const auto& pair : Sorts::nameToSort())
        {
            ostr << declareSortSMTLIB(*pair.second);
        }
        
        // output symbol definitions
        for (const auto& pairStringSymbol : Signature::signature())
        {
            ostr << pairStringSymbol.second->declareSymbolSMTLIB();
        }
        
        // output each axiom
        for (const auto& axiom : axioms)
        {
            ostr << "\n(assert\n" << axiom->toSMTLIB(3) + "\n)\n";
        }
        
        // output conjecture
        assert(conjecture != nullptr);
        
        // if benchmark is used as smtlib-benchmark, replace (assert-not F) by (assert (not F))
        if(util::Configuration::instance().generateBenchmark().getValue())
        {
            ostr
            << "\n; negated conjecture\n"
            << "(assert\n"
            << "   (not\n"
            << conjecture->toSMTLIB(6) << "\n"
            << "   )\n"
            << ")\n";
        }
        else
        {
            ostr << "\n(assert-not\n" << conjecture->toSMTLIB(3) + "\n)\n";
        }

        ostr << "\n(check-sat)\n" << std::endl;
    }
    
    std::vector<const ReasoningTask> Problem::generateReasoningTasks() const
    {
        std::vector<const ReasoningTask> tasks;
        std::vector<std::shared_ptr<const Formula>> currentAxioms;
        for (const auto& item : items)
        {
            if (item->type == ProblemItem::Type::Axiom)
            {
                currentAxioms.push_back(item->formula);
            }
         
            // if the item is a lemma or conjecture, generate a new reasoning task to prove that lemma/conjecture
            if (item->type == ProblemItem::Type::Lemma || item->type == ProblemItem::Type::Conjecture)
            {
                auto task = ReasoningTask(currentAxioms, item->formula);
                tasks.push_back(task);
            }
            
            // after generating a task to prove the lemma, the lemma can be used as axiom
            if (item->type == ProblemItem::Type::Lemma)
            {
                currentAxioms.push_back(item->formula);
            }
        }
        
        return tasks;
    }

}
